@startuml

class MainClientWindow {
	Button: Spend
	Button: Deposit
	Button: Debt
	Button: Reports

	Table Area
	Button: Add
}

class CreateTransaction {
	trxTime: auto
	trxName: text (название)
	trxSource: text (источник)
	trxSum: double (сумма)
	trxAmount: text (количество)
	category: picker (категория)
	description: text (описание)
}

class CategoryEditor {
	Button: Add
}

MainClientWindow -- CreateTransaction : onAddClick

@enduml
