-- begin YAAP_TRANSACTION
alter table YAAP_TRANSACTION add constraint FK_YAAP_TRANSACTION_ON_CATEGORY foreign key (CATEGORY_ID) references YAAP_CATEGORY(ID)^
create index IDX_YAAP_TRANSACTION_ON_CATEGORY on YAAP_TRANSACTION (CATEGORY_ID)^
-- end YAAP_TRANSACTION
-- begin YAAP_CATEGORY
alter table YAAP_CATEGORY add constraint FK_YAAP_CATEGORY_ON_PARENT foreign key (PARENT_ID) references YAAP_CATEGORY(ID)^
create index IDX_YAAP_CATEGORY_ON_PARENT on YAAP_CATEGORY (PARENT_ID)^
-- end YAAP_CATEGORY
